version: '3'
services:
  db:
    image: postgres:9.5
    environment:
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_DB=${DATABASE_NAME}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
