# Generated by Django 3.0.5 on 2020-04-28 03:09

from django.db import migrations, models
import signals.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=7)),
                ('operation_type', models.CharField(choices=[(signals.models.OperationType['SELL'], 'SELL'), (signals.models.OperationType['BUY'], 'BUY')], max_length=5)),
                ('potential_gain', models.DecimalField(decimal_places=2, max_digits=4)),
                ('potential_loss', models.DecimalField(decimal_places=2, max_digits=4)),
                ('analysis', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
