# Generated by Django 3.0.5 on 2020-04-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0003_auto_20200428_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='potential_gain',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='signal',
            name='potential_loss',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='signal',
            name='ticker',
            field=models.CharField(max_length=15),
        ),
    ]
